Commiting code. left to do - last test
ElinaLastovska/flight-planner pull request #1
Opened 2022-11-15 09:16 UTC by ElinaLastovska

2022-11-20 11:35 UTC, janistumpelis requested changes
Vispār tīri labi, paldies! Kaut kas vēl būs jāpielabo, bet to vēlāk.
Vairāk tur metožu nosaukumi pieklibo un formatting - par to gan man vairs nebūtu jākomentē, tā kā šokolāde no tevis par to 😆

2022-11-20 11:35 UTC, janistumpelis commented on frontend/generated/index.ts
> +/******************************************************************************
Šie faili iekš frontend ir lieki - kaut kā esi pielikusi klāt Vaadin failus.

2022-11-20 11:35 UTC, janistumpelis commented on package.json
> +{
Šis fails arī lieks.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/FlightsController.java
> +    private FlightsController AdminService;
Šis ir lieks, kā arī formatting failam īsti nav.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/FlightsRepository.java
> +    private final AtomicInteger id = new AtomicInteger(0);
Mainīgos liekam augšā.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/admin/AdminController.java
> +            return this.adminService.addFlight(flightRequest);
Arī formatting.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/admin/AdminService.java
> +    private final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
Mainīgos augšā.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/costumer/CostumerController.java
> +public class CostumerController {
Pieņemu, ka bija domāts Customer nevis Costumer, tas pats ar pakotni un Service klasi. :)

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/admin/AdminService.java
> +        if (ifExists(flight)){throw new ResponseStatusException(HttpStatus.CONFLICT, "Flight already exists");
Formatting arī te - man liekas Tev jāieslēdz auto formatting idea settingos.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/common/SecurityConfiguration.java
> +                .csrf().disable() //disables CSRF protection
Komentārus labāk noņem, lai visiem nav vienādi.

2022-11-20 11:35 UTC, janistumpelis commented on vite.config.ts
> +import { UserConfigFn } from 'vite';
Šitie vite. faili arī lieki.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/SearchFlightsRequest.java
> +    public SearchFlightsRequest(String from, String to, String departureDate) {
Konstruktors augšā pēc mainīgajiem, mainīgos arī taisi privātus.

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/FlightsService.java
> +    FlightsRepository flightsRepository;
private final

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/admin/AdminService.java
> +    private LocalDateTime dateTimeConverter(String dateTime) {
Metodes nosaukums - drīzāk parseDateTime

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/admin/AdminService.java
> +    public boolean ifExists (Flight flight){
Metodes nosaukums - drīzāk vienkārši `exists`

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/costumer/CostumerService.java
> +    public List<Flight> listForSearchFlight(SearchFlightsRequest searchFlightsRequest){
Nosaukums - drīzāk vienkārši `searchFlights`

2022-11-20 11:35 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/Flight.java
> +    public boolean doExistSearchFlightRequest(SearchFlightsRequest searchFlightsRequest){
Šis arī tāds interesants nosakums - 
`public boolean flightMatches(SearchFlightsRequest searchFlightsRequest){`
Un pēc tā jau ir skaidrs, ka pārbaudam vai lidojums sakrīt ar request'u

2022-11-22 09:16 UTC, ElinaLastovska commented on src/main/java/io/codelex/flightplanner/costumer/CostumerService.java
> +    public List<Flight> listForSearchFlight(SearchFlightsRequest searchFlightsRequest){
listForSearchFlight šī metode izveido sarakstu ko ievieto tai searchFlights listā.
zem šīs ir metode - searchFlights.
vai vajag savādāk? :)

2022-11-22 09:23 UTC, ElinaLastovska commented on frontend/generated/index.ts
> +/******************************************************************************
visa tā mape ir lieka?

2022-11-26 06:54 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/costumer/CostumerService.java
> +    public List<Flight> listForSearchFlight(SearchFlightsRequest searchFlightsRequest){
Attiecībā uz kodu viss tur ir ok, tikai pats nosaukums - tad varbūt liec metodi pirmkārt privātu, ja viņa nekur citur netiek izmantota, otrkārt - tad varbūt nosauc par retrieveFlights

2022-11-26 06:54 UTC, janistumpelis approved these changes

2022-12-10 17:44 UTC, janistumpelis requested changes

2022-12-10 17:44 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/AirportRepository.java
> +//    @Query("SELECT a FROM Airport a WHERE a.airport = ")
Šis laikam nav vajadzīgs.

2022-12-10 17:44 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/FlightServiceDB.java
> +public class FlightServiceDB implements FlightService {
Ok skatos, ka šeit nav pabeigts, tad taisīšu review, kad būs pabeigts.
Uzreiz ietiekums, ko redzēju kā kļūdu daudzos citos darbos, nevajag no DB izgūt visus ierakstus, lai meklētu piemēram Flight, jāmeklē ir DB pusē (jebšu citiem vārdiem sakot repository.findAll() drīkst izmantot tikai tad, kad jāatgriež visi Flight un nekur citur):
Izlasi šito un arī zemāk tajā pašā rakstā ir manual custom queries:
https://www.baeldung.com/the-persistence-layer-with-spring-data-jpa#1-automatic-custom-queries
Kā ari ir šāds vairants:
https://www.baeldung.com/spring-data-query-by-example#examples

2022-12-10 17:44 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/FlightsServiceInMemory.java
> +        return this.flightsRepository.getFlightList().stream().anyMatch(flightsInList -> flightsInList.getFrom().equals(flight.getFrom()) && flightsInList.getTo().equals(flight.getTo()) && flightsInL
Noteikti tajās garajās rindās saliec enter pa vidu (pēc && var likt), lai neizskatās tik traki.

2022-12-17 10:01 UTC, janistumpelis approved these changes
👍

2022-12-20 10:00 UTC, merged